GET http://localhost:3000/user/
###
GET http://localhost:3000/user/1

### Registrar usuarios
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "name": "pepito2",
  "email": "pepito@pepito.com",
  "birthdate": "12-10-2010",
  "nDni": "1234"
}
### Login usuarios

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "userName": "ricardoaot@gmail.com",
  "password": "45107639"
}

### Get Appointments
GET http://localhost:3000/appointment/

### Schedule Appointment
POST http://localhost:3000/appointment/schedule
Content-Type: application/json

{
    "date": "2024-05-08",
    "time": "12:00",
    "userId": "1"
}


### Cancel Appointment
PUT http://localhost:3000/appointment/cancel/1
